FROM debian:8

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get -qq update && apt-get install -qq apt-utils apt-transport-https \
 && apt-get install -qq -y ansible \
 && apt-get autoremove \
 && apt-get clean

RUN mkdir /tmp/ansible
WORKDIR /tmp/ansible
ADD local.yml /tmp/ansible/local.yml
ADD defaults /tmp/ansible/defaults
ADD tasks /tmp/ansible/tasks
RUN ansible-playbook -i localhost, local.yml -e "@defaults/main.yml"
