---
# Install the base operating system requirements for running Galaxy

- include: packages.yml
  when: install_packages

- include: system_users.yml
  when: add_system_users

- include: misc.yml
  when: install_packages
