---
# Install the base operating system requirements for running Galaxy

- include_tasks: system_users.yml
  when: add_system_users

- include_tasks: ubuntu/packages.yml
  when: install_packages and ansible_distribution == 'Ubuntu'

- include_tasks: ubuntu/docker.yml
  when: configure_docker and ansible_distribution == 'Ubuntu'

- include_tasks: debian/packages.yml
  when: install_packages and ansible_distribution == 'Debian'

- include_tasks: debian/docker.yml
  when: configure_docker and ansible_distribution == 'Debian'

- include_tasks: debian/rabbitmq.yml
  when: install_rabbitmq and ansible_os_familty == 'Debian'

- include_tasks: redhat/packages.yml
  when: install_packages and ansible_os_family == 'RedHat'
