- name: Symlink trackster required binaries to /usr/bin since trackster specifically looks for them there
  file: src={{ galaxyFS_base_dir }}/tools/bin/{{ item }} dest=/usr/bin/{{ item }} state=link force=yes
  with_items:
    - wigToBigWig
    - bedGraphToBigWig
    - faToTwoBit
  sudo: yes
  sudo_user: root
